[BOS]
cameras_number = 2
cameras_spacing = 1 # in camera fov
screen_pattern_file = "data/bos_pattern.png"
distance_camera_screen = 10 # in meters
height = 1 # in meters

[camera]
sensor_size = 5.6 # in milimeters
resolution_x = 1920
resolution_y = 1080
focal_length = 50 # in milimeters
bit_depth = "16"

[distortions]
object = 0
object_path = "data/torus.blend"
object_distance = 0.5
object_scale = 0.5
turbulence = 1 # flag to add turbulence
turbulence_path = ["data/turbulence_screen.tiff","data/turbulence_screen.tiff"]
turbulence_distance = [0.7, 0.8] # from camera (0) to screen (1)
turbulence_speed = [0] # in m/s
turbulence_strengh = [1,1]
turbulence_direction = [0] # Angle in degree

[environment]
ambiant_light_strengh = 4
dome_walls = 1
telescope = 0

[render]
activate_render = 0
format = "TIFF"
render_path = "outputs/render_results/"
active_cameras = "all" # or [camNumber1,camNumber2,...]
